### PR TITLE
hotfix modbus read throw [object object] error

### PR DESCRIPTION
**Pull request by AimeeQiu**
hotfix modbus read throw [object object] error,fix issues url : https://github.com/BiancoRoyal/node-red-contrib-modbus/issues/209

### CODE REVIEW

**Comment by biancode** [comment]
Hi @AimeeQiu , thank you for the PR! What is the point of that fix, please? If we have an err.message, then it should be an Error object - if not it will crash in the same way, right? An wrapping into an Error object is maybe not enough here, isn't it?

**Comment by AimeeQiu** [comment]
> 
> 
> Hi @AimeeQiu , thank you for the PR! What is the point of that fix, please? If we have an err.message, then it should be an Error object - if not it will crash in the same way, right? An wrapping into an Error object is maybe not enough here, isn't it?
----------------------------------------------------------------------------------------------------------------------------------------
Hi @biancode , you are right,  But modbus-serial package throw PortNotOpenError、BadAddressError、TransactionTimedOutError, the error message is always [object Object], so I use this method to solve this problem

**Comment by biancode** [comment]
Hi @AimeeQiu ah OK - I'll check this in the next few days. Thank you for the new hint!

**Comment by biancode** [comment]
released with 5.14.1

**Pull request merged**
